<?xml version="1.0" encoding="utf-8"?><Database Name="GetInfo" Class="ZhuaQuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=GetInfo;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GetInfoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MsgInfo" Member="MsgInfo">
    <Type Name="MsgInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pubdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>